/*!
 * \file
 * \brief Program to convert .dat files generated by the PEG program to .alist format
 * \author Michael Meidlinger
 *
 * -------------------------------------------------------------------------
 *
 * Copyright (C) 2016 Michael Meidlinger - All Rights Reserved
 *
 */

#include <itpp/itbase.h>
#include "LDPC_DE.hpp"

using namespace itpp;
using namespace std;
int main(int argc, char **argv){
    // Parse file name
    if(argc!=4){
        cout << "Usage: lam2max ensemble.ens  sig Nbits" << endl;
        return EXIT_FAILURE;
    }
    
    string filename(argv[1]);
    double sig = stod(string(argv[2]));
    int Nbit =  atoi(argv[3]);
    LDPC_Ensemble ens(filename);
    
    vec rho = ens.get_chk_degree_dist();
    cout << "Lam2stable LUT = " << get_lam2stable_lut(sig, rho ,  pow2(Nbit), pow2(Nbit) , 25.0, 5000) << endl;
    cout << "Lam2stable quantized BP, limit = " <<  get_lam2stable_qbp(sig, rho,  pow2(Nbit) , 25.0, 5000) << endl;
    cout << "Lam2stable BP analytical full resolution = " << get_lam2stable_cbp(sig, rho) << endl;
 //   cout << "Lam2stable quantized BP, iterative calculation = " <<  get_lam2stable_qbp_iterative(sig, rho,  pow2(Nbit) , 40.0, pow2i(15)) << endl;
    
    return EXIT_SUCCESS;
}
